vich_uploader:
    db_driver: orm
    mappings:
        property_image:
            uri_prefix: '%app.path.property_image%'
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: true # injecte l'image au chargement du formulaire
            delete_on_update: true
            delete_on_remove: true

