vich_uploader:
    db_driver: orm
    mappings:
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/images/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
