<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuCP5zE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuCP5zE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWuCP5zE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWuCP5zE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWuCP5zE\App_KernelDevDebugContainer([
    'container.build_hash' => 'WuCP5zE',
    'container.build_id' => '07d3c266',
    'container.build_time' => 1581351020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuCP5zE');
