<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ZiKJxF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ZiKJxF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5ZiKJxF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5ZiKJxF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5ZiKJxF\App_KernelDevDebugContainer([
    'container.build_hash' => '5ZiKJxF',
    'container.build_id' => '804d6b02',
    'container.build_time' => 1581343154,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ZiKJxF');
